CREATE TABLE BOOKS(
    ISBN VARCHAR(32) PRIMARY KEY,
    NAME VARCHAR(255),
    AUTHOR VARCHAR(255),
    COUNT_OF_COPY INT
);

CREATE TABLE READERS(
    ID INT PRIMARY KEY,
    FNAME VARCHAR(255),
    LNAME VARCHAR(255)
);

CREATE TABLE READERS_BOOKS(
    READER_ID INT REFERENCES READERS(ID),
    BOOK_ISBN VARCHAR(32) REFERENCES BOOKS(ISBN)
);


INSERT INTO READERS(ID, FNAME, LNAME)
VALUES
(1, 'Azizbek', 'Seitmagambetov'),
(2, 'Ibragim', 'Kuanyshbay'),
(3, 'Ayan', 'Sultan');